id = "emerald"
name = "Emerald Theme"
version = "0.0.1"
schema_version = 1
authors = ["Andrew Carter <ascarter>"]
description = "Minimal typography-focused theme for Zed editor."
repository = "https://github.com/ascarter/zed-emerald-theme"
